matrix:
    include:
        - os: linux
          sudo: false
          language: r
          pandoc_version: 1.18
          addons:
            apt:
              packages:
              - ghc
              - cabal-install
          install:
              - pip install --user pandocfilters
              - tlmgr install latexmk physics cancel fourier utopia
              - cabal update
              - cabal install --allow-newer=base pandoc-csv2table
              - cabal install -f inlineMarkdown pandoc-placetable
          cache:
            packages: true
            pip: true
            directories:
            - $HOME/.ghc
            - $HOME/.cabal
            - $HOME/.stack
script:
    - make -j4
