matrix:
    include:
        - os: linux
          sudo: false
          language: r
          pandoc_version: 1.18
          install:
              - pip install --user pandocfilters
              - tlmgr install latexmk physics cancel fourier utopia
              - cabal install --force-reinstalls --allow-newer=base pandoc-csv2table
              - cabal install --force-reinstalls -f inlineMarkdown pandoc-placetable
          cache:
            packages: true
            pip: true
            directories:
            - $HOME/.ghc
            - $HOME/.cabal
            - $HOME/.stack
script:
    - make -j4
