language: python
cache:
  - pip
# build matrix: different python and pandoc versions
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  # pypy (version info from [Changelogs — PyPy documentation](http://doc.pypy.org/en/latest/index-of-whatsnew.html))
  - "pypy"
  - "pypy3.5"
# matrix:
#   allow_failures:
#     - python: "nightly"
#   fast_finish: true
before_install:
  - pip install -U pip
  - pip install -r requirements.txt
  - pip install -e .[test]
install:
  - python setup.py sdist bdist_wheel
# command to run tests
script:
  - make -j3 test
after_success:
  - |
    [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]] && coveralls
deploy:
  provider: pypi
  user: ickc
  password: $pypi_password
  skip_cleanup: true
  on:
    tags: true
    python: "3.6"
