# os: linux and sudo: false is assumed, which means it is using container-based Ubuntu 12.04
language: python
cache:
  - pip
# build matrix: different python and pandoc versions
python:
  - "3.3"
  - "3.4"
  - "3.5"
  # - "3.5-dev" # 3.5 development branch
  # - "3.6-dev" # 3.6 development branch
  # - "nightly" # currently points to 3.7-dev
  # - "pypy3"
matrix:
  allow_failures:
    - python: "3.5-dev"
    - python: "3.6-dev"
    - python: "nightly"
    - python: "pypy3"
  fast_finish: true
install:
  - pip install -U pip
  - pip install -r requirements.txt
  - pip install -e .[test]
# command to run tests
script:
  - make -j4 pytest
after_success:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "3.5" ]]; then coveralls; else printf "skip coveralls"; fi;
deploy:
  provider: pypi
  user: ickc
  password: $pypi_password
  skip_cleanup: true
  on:
    tags: true
    python: "3.5"
