matrix:
    include:
        - os: linux
          sudo: required
          dist: trusty
          language: r
          pandoc_version: 1.18
          before_install:
              - sudo apt-get -qq update
              - sudo apt-get ghc 
              - sudo apt-get cabal-install
          install:     
              - pip install --user pandocfilters
              - tlmgr install latexmk physics cancel fourier utopia
              - cabal update
              - cabal install --allow-newer=base pandoc-csv2table
              - cabal install -f inlineMarkdown pandoc-placetable
          cache:
            packages: true
            pip: true
            directories:
            - $HOME/.ghc
            - $HOME/.cabal
            - $HOME/.stack
script:
    - make -j4
