matrix:
    include:
        - os: linux
          sudo: required
          dist: trusty
          language: r
          addons:
            apt:
              packages:
              - ghc
              - cabal-install
          install:
              - pip install -U pandocfilters tabulate terminaltables astropy openpyxl pillow pyyaml
              - tlmgr install latexmk physics cancel fourier utopia
              - cabal update
              - cabal install pandoc pandoc-csv2table
              - cabal install -f inlineMarkdown pandoc-placetable
          cache:
            packages: true
            pip: true
            directories:
            - $HOME/.ghc
            - $HOME/.cabal
            - $HOME/.stack
script:
    - export PATH="$HOME/.cabal/bin:$PATH" && make -j4
